---
name: Auto-merge Dependabot PRs

"on":
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auto-approve Dependabot PRs
        if: github.actor == 'dependabot[bot]'
        run: |
          gh pr review --approve "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label Dependabot PRs
        if: github.actor == 'dependabot[bot]'
        run: |
          gh pr edit "${{ github.event.pull_request.number }}" --add-label "dependencies"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}