name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate PowerShell syntax
        shell: pwsh
        run: |
          Get-ChildItem -Path . -Filter "*.ps1" -Recurse | ForEach-Object {
            Write-Host "Validating: $($_.Name)"
            $null = [System.Management.Automation.PSParser]::Tokenize((Get-Content $_.FullName -Raw), [ref]$null)
            Write-Host "✅ $($_.Name) syntax is valid"
          }
          
      - name: Validate JSON files
        run: |
          find . -name "*.json" -type f | while read file; do
            echo "Validating: $file"
            python -m json.tool "$file" > /dev/null
            echo "✅ $file is valid JSON"
          done
          
      - name: Validate YAML files
        run: |
          sudo apt-get update && sudo apt-get install -y yamllint
          find . -name "*.yml" -o -name "*.yaml" | while read file; do
            echo "Validating: $file"
            yamllint "$file"
            echo "✅ $file is valid YAML"
          done
          
      - name: Check for sensitive data
        run: |
          if grep -r -i "password\|secret\|key\|token" --include="*.ps1" --include="*.json" --include="*.yml" .; then
            echo "❌ Potential sensitive data found"
            exit 1
          else
            echo "✅ No sensitive data detected"
          fi
