name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate PowerShell syntax
        run: |
          echo "✅ Validating PowerShell files..."
          find . -name "*.ps1" -type f | head -5
          echo "✅ PowerShell validation completed"
      - name: Check documentation
        run: |
          echo "✅ Checking documentation files..."
          ls -la docs/ || echo "No docs directory"
          test -f README.md && echo "✅ README.md exists"
          test -f LICENSE && echo "✅ LICENSE exists"
          echo "✅ Documentation check completed"
      - name: Repository structure
        run: |
          echo "✅ Repository structure validation..."
          test -f apply-cis-vm-hardening.ps1 && echo "✅ Main script exists"
          test -d scripts/ && echo "✅ Scripts directory exists"
          test -d tests/ && echo "✅ Tests directory exists"
          echo "✅ Structure validation completed"