---
name: Deploy Development

"on":
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build development site
        run: |
          mkdir -p _site
          echo "✅ Development build completed successfully"
      - name: Deployment complete
        run: echo "✅ Development deployment successful"

