name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PowerShell
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Validate Script
      shell: pwsh
      run: |
        Write-Host "Validating PowerShell script..." -ForegroundColor Green
        if (Test-Path ./apply-cis-vm-hardening.ps1) {
          Write-Host "✅ Script file exists" -ForegroundColor Green
        } else {
          Write-Error "❌ Script file not found"
        }

    - name: Check Syntax
      shell: pwsh
      run: |
        try {
          $content = Get-Content ./apply-cis-vm-hardening.ps1 -Raw
          $null = [System.Management.Automation.PSParser]::Tokenize($content, [ref]$null)
          Write-Host "✅ PowerShell syntax is valid" -ForegroundColor Green
        } catch {
          Write-Error "❌ PowerShell syntax error: $($_.Exception.Message)"
        }