name: Weekly Activity

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  security-events: write
  actions: read

  schedule:
    - cron: "0 10 * * 1"  # Every Monday at 10:00 UTC
  workflow_dispatch:

